[[sloka]]
should_number = false
add_punctuation = false
lines = """
shrI paramAtmane namaH
atha chaturtho.adhyAyaH
j~nAna-yogaH"""

[[sloka]]
lines = """
shrI bhagavAnuvAcha
imaM vivasvate yogaM
proktavA-naha-mavyayam
vivasvAn-manave prAha
manurikShvA-kave.abravIt"""

[[sloka]]
lines = """
evaM paramparA-prAptam
imaM rAjarShayo viduH
sa kAleneha mahatA
yogo naShTaH parantapa"""

[[sloka]]
lines = """
sa evAyaM mayA te.adya
yogaH proktaH purAtanaH
bhakto.asi me sakhA ceti
rahasyaM hyeta-duttamam"""

[[sloka]]
lines = """
arjuna uvAcha
aparaM bhavato janma
paraM janma vivasvataH
kathameta-dvijAnIyAM
tvamAdau proktavAniti"""

[[sloka]]
lines = """
shrI bhagavAnuvAcha
bahUni me vyatItAni
janmAni tava chArjuna
tAnyahaM veda sarvANi
na tvaM vettha parantapa"""

[[sloka]]
lines = """
ajo.api san-navya-yAtmA
bhUtAnA-mIshvaro.api san
prakRRitiM svAma-dhiShThAya
sambhavA-myAt-mamA-yayA"""

[[sloka]]
lines = """
yadA yadA hi dharmasya
glAnir-bhavati bhArata
abhyutthAna-madharmasya
tadA.a.atmAnaM sRRijAmyaham"""

[[sloka]]
lines = """
paritrANAya sAdhUnAM
vinAshAya cha duShkRRitAm
dharma-saMsthApa-nArthAya
sambhavAmi yuge yuge"""

[[sloka]]
lines = """
janma karma cha me divyam
evaM yo vetti tattvataH
tyaktvA dehaM punarjanma
naiti mAmeti so.arjuna"""

[[sloka]]
lines = """
vItarAga-bhaya-krodhAH
manmayA mAmu-pAshritAH
bahavo j~nAna-tapasA
pUtA madbhAva-mAgatAH"""

[[sloka]]
lines = """
ye yathA mAM prapadyante
tAMstathaiva bhajAmyaham
mama vartmAnu-vartante
manuShyAH pArtha sarvashaH"""

[[sloka]]
lines = """
kA~NkShantaH karmaNAM siddhiM
yajanta iha devatAH
kShipraM hi mAnuShe loke
siddhir-bhavati karmajA"""

[[sloka]]
lines = """
chAtur-varNyaM mayA sRRiShTaM
guNa-karma-vibhAgashaH
tasya kartAra-mapi mAM
viddhya-kartAra-mavyayam"""

[[sloka]]
lines = """
na mAM karmANi limpanti
na me karmaphale spRRihA
iti mAM yo.abhijAnAti
karmabhirna sa badhyate"""

[[sloka]]
lines = """
evaM j~nAtvA kRRitaM karma
pUrvairapi mumukShubhiH
kuru karmaiva tasmAttvaM
pUrvaiH pUrva-taraM kRRitam"""

[[sloka]]
lines = """
kiM karma kima-karmeti
kavayo.apyatra mohitAH
tatte karma·pravakShyAmi
yaj-j~nAtvA mokShyase.ashubhAt"""

[[sloka]]
lines = """
karmaNo hyapi boddhavyaM
boddhavyaM cha vikarmaNaH
akarmaNashcha boddhavyaM
gahanA karmaNo gatiH"""

[[sloka]]
lines = """
karmaNya-karma yaH pashyet
akarmaNi-cha karma yaH
sa buddhimAn-manuShyeShu
sa yuktaH kRRitsna-karmakRRit"""

[[sloka]]
lines = """
yasya sarve samA-rambhAH
kAma-sa~Nkalpa-varjitAH
j~nAnAgni-dagdha-karmANaM
tamAhuH paNDitaM budhAH"""

[[sloka]]
lines = """
tyaktvA karma-phalAsa~NgaM
nitya-tRRipto nirAshrayaH
karmaNyabhi-pravRRitto.api
naiva ki~nchitkaroti saH"""

[[sloka]]
lines = """
nirAshIr-yatachittAtmA
tyaktasarva parigrahaH
shArIraM kevalaM karma
kurvannApnoti kilbiSham"""

[[sloka]]
lines = """
yadRRichChAlA-bhasantuShTaH
dvandvAtIto vimatsaraH
samaH siddhAva-siddhau cha
kRRitvApi na nibadhyate"""

[[sloka]]
lines = """
gatasa~Ngasya muktasya
j~nAnA-vasthita-chetasaH
yaj~nA-yAcharataH karma
samagraM pravilIyate"""

[[sloka]]
lines = """
brahmArpaNaM brahma haviH
brahmAgnau brahmaNA hutam
brahmaiva tena gantavyaM
brahma-karma-samAdhinA"""

[[sloka]]
lines = """
daiva-mevApare yaj~naM
yoginaH paryupAsate
brahmAgnA-vapare yaj~naM
yaj~ne-naivopa-juhvati"""

[[sloka]]
lines = """
shrotrA-dInIndriyAN-yanye
saMya-mAgniShu juhvati
shabdAdIn-viShayAn-anye
indriyA-gniShu juhvati"""

[[sloka]]
lines = """
sarvAN-Indriya-karmANi
prANa-karmANi chApare
Atma-saMyama-yogAgnau
juhvati·j~nAna-dIpite"""

[[sloka]]
lines = """
dravya-yaj~nAstapo-yaj~nAH
yoga-yaj~nAs-tathA.apare
svAdhyA-yaj~nA-nayaj~nAshcha
yatayaH saM-shita-vratAH"""

[[sloka]]
lines = """
apAne juhvati·prANaM
prANe.apAnaM tathApare
prANApAna-gatI ruddhvA
prANAyAma-parAyaNAH"""

[[sloka]]
lines = """
apare niyatAhArAH
prANAn-prANeShu juhvati
sarve.apyete yaj~na-vidaH
yaj~na-kShapita-kalmaShAH"""

[[sloka]]
lines = """
yaj~na-shiShTAmRRita-bhujaH
yAnti·brahma sanAtanam
nAyaM loko.astya-yaj~nasya
kuto.anyaH kurusattama"""

[[sloka]]
lines = """
evaM bahuvidhA yaj~nAH
vitatA brahmaNo mukhe
karma-jAnviddhi tAnsarvAn
evaM j~nAtvA vimokShyase"""

[[sloka]]
lines = """
shreyAn-dravya-mayAd-yaj~nAt
j~nAna-yaj~naH parantapa
sarvaM karmAkhilaM pArtha
j~nAne parisa-mApyate"""

[[sloka]]
lines = """
tadviddhi·praNipAtena
pari-prashnena sevayA
upadekShyanti te·j~nAnaM
j~nAnina-stattva-darshinaH"""

[[sloka]]
lines = """
yaj-j~nAtvA na punarmoham
evaM yAsyasi pANDava
yena bhUtAnya-sheSheNa
drakShyasyAt-manyatho mayi"""

[[sloka]]
lines = """
api chedasi pApebhyaH
sarvebhyaH pApakRRittamaH
sarvaM j~nAna-plavenaiva
vRRijinaM santariShyasi"""

[[sloka]]
lines = """
yathai-dhAMsi samiddho.agniH
bhasmasAt-kurute.arjuna
j~nAnAgniH sarva-karmANi
bhasmasAt-kurute tathA"""

[[sloka]]
lines = """
na hi·j~nAnena sadRRishaM
pavitra-miha vidyate
tat-svayaM yoga-saMsiddhaH
kAlenAtmani vindati"""

[[sloka]]
lines = """
shraddhAvAn labhate j~nAnaM
tatparaH saM-yatendriyaH
j~nAnaM labdhvA parAM shAntim
achireNAdhi-gachChati"""

[[sloka]]
lines = """
aj~nashchA-shraddadhAnashcha
saMshayAtmA vinashyati
nAyaM loko.asti na paraH
na sukhaM saMshayAtmanaH"""

[[sloka]]
lines = """
yoga-sannyasta-karmANaM
j~nAna-sa~nChinna-saMshayam
Atma-vantaM na karmANi
nibadhnanti dhana~njaya"""

[[sloka]]
lines = """
tasmAda-j~nAna-sambhUtaM
hRRitsthaM j~nAnA-sinAtmanaH
ChittvainaM saMshayaM yogam
AtiShThottiShTha bhArata"""

[[sloka]]
should_number = false
add_punctuation = false
lines = """
shrImad-bhagavad-gItAsu upaniShatsu
brahma-vidyAyAM yogashAstre
shrIkRRiShNArjuna saMvAde
j~nAna-yogonAma
chaturtho-dhyAyaH"""