[[sloka]]
should_number = false
add_punctuation = false
lines = """
shrI paramAtmane namaH
atha prathamo.adhyAyaH
arjuna-viShAda-yogaH"""

[[sloka]]
lines = """
dhRRitarAShTra uvAcha
dharmakShetre kurukShetre
samavetA yuyutsavaH
mAmakAH pANDavAshchaiva
kimakurvata sa~njaya"""

[[sloka]]
lines = """
sa~njaya uvAcha
dRRiShTvA tu pANDavAnIkaM
vyUDhaM duryodhanastadA
AchAryamupasa~Ngamya
rAjA vachanama-bravIt"""

[[sloka]]
lines = """
pashyaitAM pANDu-putrANAm
AchArya mahatIM chamUm
vyUDhAM drupada-putreNa
tava shiShyeNa dhImatA"""

[[sloka]]
lines = """
atra shUrA maheShvAsAH
bhImArjuna-samA yudhi
yuyudhAno virATashcha
drupadashcha mahArathaH"""

[[sloka]]
lines = """
dhRRiShTa-ketushchekitAnaH
kAshirAjashcha vIryavAn
purujit-kunti-bhojashcha
shaibyashcha narapu~NgavaH"""

[[sloka]]
lines = """
yudhA-manyushcha vikrAntaH
uttamaujAshcha vIryavAn
saubhadro draupadeyAshcha
sarva eva mahArathAH"""

[[sloka]]
lines = """
asmAkaM tu vishiShTA ye
tAnni-bodha路dvijottama
nAyakA mama sainyasya
sa~nj~nArthaM tAnbravImi te"""

[[sloka]]
lines = """
bhavAn-bhIShmashcha karNashcha
kRRipashcha samiti~njayaH
ashvatthAmA vikarNashcha
saumadattista-thaiva cha"""

[[sloka]]
lines = """
anye cha bahavaH shUrAH
madarthe tyakta-jIvitAH
nAnAshastra-praharaNAH
sarve yuddha-vishAradAH"""

[[sloka]]
lines = """
aparyAptaM tadas-mAkaM
balaM bhIShmA-bhirakShitam
paryAptaM tvidame-teShAM
balaM bhImA-bhirakShitam"""

[[sloka]]
lines = """
ayaneShu cha sarveShu
yathA-bhAgama-vasthitAH
bhIShmamevA-bhirakShantu
bhavantaH sarva eva hi"""

[[sloka]]
lines = """
tasya sa~njana-yanharShaM
kuruvRRiddhaH pitAmahaH
siMhanAdaM vina-dyochchaiH
sha~NkhaM dadhmau pratApavAn"""

[[sloka]]
lines = """
tataH sha~NkhAshcha bheryashcha
paNavAnaka-gomukhAH
saha-saivAbhya-hanyanta
sa shabda-stumulo.abhavat"""

[[sloka]]
lines = """
tataH shvetair-hayair-yukte
mahati路syan-dane sthitau
mAdhavaH pANDavashchaiva
divyau sha~Nkhau pradadhmatuH"""

[[sloka]]
lines = """
pA~ncha-janyaM hRRiShIkeshaH
devadattaM dhana~njayaH
pauNDraM dadhmau mahA-sha~NkhaM
bhIma-karmA vRRikodaraH"""

[[sloka]]
lines = """
ananta-vijayaM rAjA
kuntIputro yudhiShThiraH
nakulaH saha-devashcha
sugho-ShamaNi-puShpakau"""

[[sloka]]
lines = """
kAshyashcha parameShvAsaH
shikhaNDI cha mahArathaH
dhRRiShTa-dyumno virATashcha
sAtyakishchA-parAjitaH"""

[[sloka]]
lines = """
drupado draupadeyAshcha
sarvashaH pRRithivIpate
soubhad-rashcha mahAbAhuH
sha~NkhAn-dadhmuH pRRithak-pRRithak"""

[[sloka]]
lines = """
sa ghoSho dhArta-rAShTrANAM
hRRidayAni路vyadArayat
nabhashcha pRRithivIM chaiva
tumulo vyanu-nAdayan"""

[[sloka]]
lines = """
atha路vya-vasthitAn-dRRiShTvA
dhArta-rAShTrAn kapidhvajaH
pravRRitte shastra-sampAte
dhanu-rudyamya pANDavaH"""

[[sloka]]
add_punctuation = false
lines = """
hRRiShIkeshaM tadA vAkyam
idamAha mahIpate
arjuna uvAcha
senayor-ubhayor-madhye
rathaM sthApaya me.achyuta"""

[[sloka]]
lines = """
yAvadetAn-nirIkShe.ahaM
yoddhu-kAmAna-vasthitAn
kairmayA saha yoddhavyam
asmin raNa-samudyame"""

[[sloka]]
lines = """
yotsya-mAnA-navekShe.ahaM
ya ete.atra samAgatAH
dhArta-rAShTrasya-durbuddheH
yuddhe priya-chikIrShavaH"""

[[sloka]]
lines = """
sa~njaya uvAca
evamukto hRRiShIkeshaH
guDAkeshena bhArata
senayor-ubhayor-madhye
sthApa-yitvA rathottamam"""

[[sloka]]
lines = """
bhIShma-droNa-pramukhataH
sarveShAM ca mahIkShitAm
uvAca pArtha pashyaitAn
sama-vetAn-kurUniti"""

[[sloka]]
lines = """
tatrA-pashyat-sthitAn-pArthaH
pitRRInatha pitAmahAn
AcAryAn-mAtulAn-bhrAtRRIn
putrAn-pautrAn-sakhIM-stathA"""

[[sloka]]
lines = """
shvashurAn-suhRRidashcaiva
senayor-ubhayorapi
tAnsamIkShya sa kaunteyaH
sarvAn-bandhUna-vasthitAn"""

[[sloka]]
lines = """
kRRipayA parayA.a.aviShTaH
viShIdannidama-bravIt
arjuna uvAca
dRRiShTvemaM svajanaM kRRiShNa
yuyutsuM samupasthitam"""

[[sloka]]
lines = """
sIdanti mama gAtrANi
mukhaM ca parishuShyati
vepathushca sharIre me
romaharShashca jAyate"""

[[sloka]]
lines = """
gANDIvaM sraMsate hastAt
tvakcaiva pari-dahyate
na ca shaknomya-vasthAtuM
bhramatIva ca me manaH"""

[[sloka]]
lines = """
nimittAni ca pashyAmi
viparItAni keshava
na ca shreyo.anupashyAmi
hatvA svajana-mAhave"""

[[sloka]]
lines = """
na kA~NkShe vijayaM kRRiShNa
na ca rAjyaM sukhAni ca
kiM no rAjyena govinda
kiM bhogair-jIvitena vA"""

[[sloka]]
lines = """
yeShAmarthe kA~NkShitaM naH
rAjyaM bhogAH sukhAni ca
ta ime.avasthitA yuddhe
prANAM-styaktvA dhanAni ca"""

[[sloka]]
lines = """
AcAryAH pitaraH putrAH
tathaiva ca pitA-mahAH
mAtulAH shvashurAH pautrAH
shyAlAH samban-dhinastathA"""

[[sloka]]
lines = """
etAnna hantumicchAmi
ghnato.api madhu-sUdana
api trailokya-rAjyasya
hetoH kiM nu mahIkRRite"""

[[sloka]]
lines = """
nihatya dhArta-rAShTrAnnaH
kA prItiH syAjjanArdana
pApamevA-shraye-dasmAn
hatvaitAnA-tatAyinaH"""

[[sloka]]
lines = """
tasmAn-nArhA vayaM hantuM
dhArtarAShTrAn-svabAndhavAn
svajanaM hi kathaM hatvA
sukhinaH syAma mAdhava"""

[[sloka]]
lines = """
yadyapyete na pashyanti
lobho-pahata-cetasaH
kula-kShaya-kRRitaM doShaM
mitra-drohe ca pAtakam"""

[[sloka]]
lines = """
kathaM na j~neya-masmAbhiH
pApAdasmAn-nivartitum
kula-kShaya-kRRitaM doShaM
prapashyad-bhir-janArdana"""

[[sloka]]
lines = """
kula-kShaye praNashyanti
kuladharmAH sanAtanAH
dharme naShTe kulaM kRRitsnam
adharmo.abhi-bhavatyuta"""

[[sloka]]
lines = """
adharmAbhi-bhavAt-kRRiShNa
praduShyanti kula-striyaH
strIShu duShTAsu vArShNeya
jAyate varNa-sa~NkaraH"""

[[sloka]]
lines = """
sa~Nkaro narakAyaiva
kulaghnAnAM kulasya ca
patanti pitaro hyeShAM
lupta-piNDo-daka-kriyAH"""

[[sloka]]
lines = """
doShairetaiH kula-ghnAnAM
varNa-sa~Nkara-kArakaiH
utsAdyante jAtidharmAH
kula-dharmAshca shAshvatAH"""

[[sloka]]
lines = """
utsannakula-dharmANAM
manuShyANAM janArdana
narake.aniyataM vAsaH
bhavatI-tyanushushruma"""

[[sloka]]
lines = """
aho bata mahat-pApaM
kartuM vyava-sitA vayam
yadrAjya-sukha-lobhena
hantuM svajana-mudyatAH"""

[[sloka]]
lines = """
yadi mAma-pratIkAram
ashastraM shastra-pANayaH
dhArtarAShTrA raNe hanyuH
tanme kShe-mataraM bhavet"""

[[sloka]]
lines = """
sa~njaya uvAca
evamuktvA.arjunaH sa~Nkhye
rathopastha upAvishat
visRRijya sasharaM cApaM
shokasaM-vigna-mAnasaH"""

[[sloka]]
should_number = false
add_punctuation = false
lines = """
shrImad-bhagavad-gItAsu upaniShatsu
brahma-vidyAyAM yogashAstre
shrIkRRiShNArjuna saMvAde
arjuna-viShAda-yogonAma
prathamo-dhyAyaH"""

