[[sloka]]
should_number = false
add_punctuation = false
lines = """
shrI paramAtmane namaH
atha dvAdasho.adhyAyaH
bhakti-yogaH"""

[[sloka]]
lines = """
arjuna uvAcha
evaM satatayuktA ye
bhaktAstvAM paryupAsate
ye chApyakSharam-avyaktaM
teShAM ke yogavittamAH"""

[[sloka]]
lines = """
shrI bhagavAn uvAcha
mayyAveshya mano ye mAM
nityayuktA upAsate
shraddhayA parayopetAH
te me yuktatamA matAH"""

[[sloka]]
lines = """
ye tvakSharam-anirdeshyam
avyaktaM paryupAsate
sarvatragam-achintyam cha
kUTastha-machalam dhruvaM"""

[[sloka]]
lines = """
sanniyamyendriya-grAmaM
sarvatra samabuddhayaH
te prApnuvanti mAmeva
sarvabhUtahite ratAH"""

[[sloka]]
lines = """
klesho.adhika-tarasteShAm
avyaktAsakta-chetasAm
avyaktA hi gatirduHkhaM
dehavad-bhiravApyate"""

[[sloka]]
lines = """
ye tu sarvANi karmANi
mayi sannyasya matparAH
ananyenaiva yogena
mAM dhyAyanta upAsate"""

[[sloka]]
lines = """
teShAmahaM samuddhartA
mRRityu-saMsAra-sAgarAt
bhavAmi nacirAt-pArtha
mayyAveshita-chetasAm"""

[[sloka]]
lines = """
mayyeva mana Adhatsva
mayi buddhiM niveshaya
nivasiShyasi mayyeva
ata UrdhvaM na samshayaH"""

[[sloka]]
lines = """
atha chittaM samAdhAtuM
na shaknoShi mayi sthiram
abhyAsayogena tataH
mAmichChAptuM dhana~njaya"""

[[sloka]]
lines = """
abhyAse.apyasamartho.asi
mat-karma-paramo bhava
madarthamapi karmANi
kurvan-siddhi-mavApsyasi"""

[[sloka]]
lines = """
athaitadapyashakto.asi
kartuM mad-yogam-AshritaH
sarva-karma-phala-tyAgaM
tataH kuru yatAtmavAn"""

[[sloka]]
lines = """
shreyo hi·j~nAnam-abhyAsAt
j~nAnAddhyAnaM vishiShyate
dhyAnAt-karma-phala-tyAgaH
tyAgAchChAntiranantaram"""

[[sloka]]
lines = """
adveShTA sarvabhUtAnAM
maitraH karuNa eva cha
nirmamo nirahankAraH
sama-duHkha-sukhaH·kShamI"""

[[sloka]]
lines = """
santuShTaH satataM yogI
yatAtmA dRRiDha-nishchayaH
mayyarpitamanobuddhiH
yo madbhaktaH sa me priyaH"""

[[sloka]]
lines = """
yasmAnnodvijate lokaH
lokAnnodvijate cha yaH
harShAmarSha-bhayodvegaiH
mukto yaH sa cha me priyaH"""

[[sloka]]
lines = """
anapekShaH shuchirdakShaH
udAsIno gatavyathaH
sarvArambha-parityAgI
yo madbhaktaH sa me priyaH"""

[[sloka]]
lines = """
yo na hRRiShyati na·dveShTi
na shochati na kA~nkShati
shubhAshubha-parityAgI
bhaktimAnyaH sa me priyaH"""

[[sloka]]
lines = """
samaH shatrau cha mitre cha
tathA mAnApamAnayoH
shItoShNa-sukha-duHkheShu
samaH sa~nga-vivarjitaH"""

[[sloka]]
lines = """
tulya-nindA-stutirmaunI
santuShTo yena kenachit
aniketaH sthiramatiH
bhaktimAnme priyo naraH"""

[[sloka]]
lines = """
ye tu dharmyAmRRitamidaM
yathoktaM paryupAsate
shraddadhAnA matparamAH
bhaktAste.atIva me priyAH"""

[[sloka]]
should_number = false
add_punctuation = false
lines = """
shrImad-bhagavad-gItAsu upaniShatsu
brahma-vidyAyAM yogashAstre
shrIkRRiShNArjuna saMvAde
bhakti-yogonAma
dvAdasho-dhyAyaH"""