name: CI
on:
  push:
    branches: [ master ]

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: LaTeX Compilation
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: gita-telugu.tex
          working_directory: latex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          target_branch: gh-pages
          keep_history: false
          build_dir: public
          # The committer name and email address
#           committer: # optional
          # The author name and email address
#           author: # optional
          # Commit message
#           commit_message: # optional
          # Write the given domain name to the CNAME file
          fqdn: gita.aduri.net
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
