name: CI
on:
  push:
    branches: [ master ]
    paths:
      - '**.tex'

    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: Telugu LaTeX Compilation
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: gita-telugu.tex
          working_directory: latex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
          
      - name: IAST LaTeX Compilation
        uses: dante-ev/latex-action@v0.2.0
        with:
          root_file: gita-iast.tex
          working_directory: latex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode

      - name: Copy Built PDF to public/
        run: cp latex/gita-*.pdf public/

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          target_branch: gh-pages
          keep_history: false
          build_dir: public
          fqdn: gita.aduri.net
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
